<a href="https://colab.research.google.com/github/umang0015/Ai-DataScience/blob/main/Deeplearning7Aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# build simple neural network model for below data
import tensorflow as tf
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
print(x, y)

[1 2 3 4 5] [5 6 7 8 9]

In [ ]:
# build the NN architecture with keras
from tensorflow import keras
#to define model type
from keras.models import Sequential
#to add input and output neurons to model (definining input and output in activation function)
from keras.layers import Dense


# define the architecture
model= Sequential()
model.add(Dense(units=1 , input_shape=(1,)))
#units =1 means output neuron is 1 , input shape define actual no. of column
model.summary()
#  define optimizer and metrics
model.compile(optimizer='sgd' , loss=['mean_squared_error'])

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x,y , epochs=100)

In [ ]:
# print the model weights
print(model.get_weights())

[array([[1.7258339]], dtype=float32), array([1.3795094], dtype=float32)]

In [ ]:
import numpy as np
# predict on sample data
print(model.predict(np.array([3])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[[6.557011]]

In [ ]:
# save the model
model.save('/content/drive/MyDrive/Models/my_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
# loading the file
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/Abeyaantrix2Internship/intern/main/Salary_Data.csv')

In [ ]:
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [ ]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [ ]:
x=df['YearsExperience']
y=df['Salary']

In [ ]:
from jax import random
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x, y , test_size=0.2 ,random_state =42)

In [ ]:
x_train

28    10.3
24     8.7
12     4.0
0      1.1
4      2.2
16     5.1
5      2.9
13     4.1
11     4.0
22     7.9
1      1.3
2      1.5
25     9.0
3      2.0
21     7.1
26     9.5
18     5.9
29    10.5
20     6.8
7      3.2
10     3.9
14     4.5
19     6.0
6      3.0
Name: YearsExperience, dtype: float64

In [ ]:
x_test

27    9.6
15    4.9
23    8.2
17    5.3
8     3.2
9     3.7
Name: YearsExperience, dtype: float64

In [ ]:
# fitting regression
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train.values.reshape(-1, 1), y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(x_test.values.reshape(-1, 1))

In [ ]:
from tensorflow import keras
#to define model type
from keras.models import Sequential
#to add input and output neurons to model (definining input and output in activation function)
from keras.layers import Dense


# define the architecture
mod= Sequential()
mod.add(Dense(units=1 , input_shape=(1,)))
#units =1 means output neuron is 1 , input shape define actual no. of column
mod.summary()
#  define optimizer and metrics
mod.compile(optimizer='sgd' , loss=['mean_squared_error'])