<a href="https://colab.research.google.com/github/umang0015/Ai-DataScience/blob/main/Generative%20AI/NLP_11_Models_model_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hugging Face Pre-Trained Models — 11 Models / 3 Tasks

## Goal

For every model:

1. Load the model.
2. Run three tasks that are **compatible with that model's architecture**.
3. Record output and inference time.
4. Compare models within the same task/model family.

> The 11 models do not all support the same pipelines. Forcing a generation or summarization pipeline onto DistilBERT, for example, would be technically incorrect. This notebook therefore keeps three experiments per model while respecting each model's architecture.

## Install Libraries

In [ ]:
!pip -q install -U transformers sentencepiece accelerate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 75.9 MB/s eta 0:00:00

## Imports and Device

In [ ]:
from transformers import pipeline
import pandas as pd
import time
import torch

device = 0 if torch.cuda.is_available() else -1

print("GPU available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

GPU available: True
GPU: Tesla T4

## Common Inputs

In [ ]:
generation_prompt = "Explain artificial intelligence in simple words."

completion_prompt = "The future of artificial intelligence is"

question = "What is artificial intelligence?"

article = '''
Artificial intelligence is a branch of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, recognizing images, and making decisions.
Modern AI systems use machine learning and deep learning techniques to
learn patterns from large amounts of data.
'''

translation_text = "Artificial intelligence is changing the way people work and learn."

# MODEL 1 — SmolLM3 3B

**Hugging Face ID:** `HuggingFaceTB/SmolLM3-3B`

**Architecture:** Causal Language Model

### Three compatible tasks
1. Text Generation
2. Text Completion
3. Prompt-Based Question Answering

In [ ]:
model_id = "HuggingFaceTB/SmolLM3-3B"

generator = pipeline(
    "text-generation",
    model=model_id,
    device=device
)

print("Loaded:", model_id)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.92k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.9k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/326 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/182 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.2MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/289 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/5.60k [00:00<?, ?B/s]

Loaded: HuggingFaceTB/SmolLM3-3B

## Task 1 — Text Generation

In [ ]:
start = time.time()

result = generator(
    generation_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample', 'num_return_sequences'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=60) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Time: 9.03 seconds
Explain artificial intelligence in simple words. A 5-year-old would understand?
AI is like a super smart helper that can learn and do things on its own, just like you do. It can understand and learn from pictures, videos, and spoken words. It can even help you find things on the internet or answer your questions. But

## Task 2 — Text Completion

In [ ]:
start = time.time()

result = generator(
    completion_prompt,
    max_new_tokens=50,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 6.63 seconds
The future of artificial intelligence is bright, but it also brings significant challenges. As AI becomes increasingly integrated into our daily lives, concerns about job displacement, bias, and accountability have been raised. To navigate these challenges, we need to focus on developing AI that is not only powerful but

## Task 3 — Prompt-Based Question Answering

In [ ]:
qa_prompt = (
    "Answer this question clearly and briefly. "
    "Question: " + question
)

start = time.time()

result = generator(
    qa_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=False
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 6.76 seconds
Answer this question clearly and briefly. Question: What is artificial intelligence? Answer: Artificial intelligence (AI) is the simulation of human intelligence processes by machines, particularly computer systems. It is a branch of computer science that focuses on creating intelligent machines that can perform tasks that typically require human intelligence, such as learning, problem-solving, and decision-making. AI systems can be designed

# MODEL 2 — DistilGPT-2

**Hugging Face ID:** `distilbert/distilgpt2`

**Architecture:** Causal Language Model

### Three compatible tasks
1. Text Generation
2. Text Completion
3. Prompt-Based Question Answering

In [ ]:
model_id = "distilbert/distilgpt2"

generator = pipeline(
    "text-generation",
    model=model_id,
    device=device
)

print("Loaded:", model_id)

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  353MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Loaded: distilbert/distilgpt2

## Task 1 — Text Generation

In [ ]:
start = time.time()

result = generator(
    generation_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Time: 0.26 seconds
Explain artificial intelligence in simple words.

## Task 2 — Text Completion

In [ ]:
start = time.time()

result = generator(
    completion_prompt,
    max_new_tokens=50,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 1.13 seconds
The future of artificial intelligence is about to start to look like something of a new phenomenon. It could mean the creation of a new field, and could allow the researchers to develop new technologies that could be used to make computers smarter, smarter, or more efficient.

## Task 3 — Prompt-Based Question Answering

In [ ]:
qa_prompt = (
    "Answer this question clearly and briefly. "
    "Question: " + question
)

start = time.time()

result = generator(
    qa_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=False
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 1.48 seconds
Answer this question clearly and briefly. Question: What is artificial intelligence?

# MODEL 3 — GPT-2

**Hugging Face ID:** `openai-community/gpt2`

**Architecture:** Causal Language Model

### Three compatible tasks
1. Text Generation
2. Text Completion
3. Prompt-Based Question Answering

In [ ]:
model_id = "openai-community/gpt2"

generator = pipeline(
    "text-generation",
    model=model_id,
    device=device
)

print("Loaded:", model_id)

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Loaded: openai-community/gpt2

## Task 1 — Text Generation

In [ ]:
start = time.time()

result = generator(
    generation_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 0.67 seconds
Explain artificial intelligence in simple words.

5. Use short phrases and phrases in your words when you're talking about the real world

6. Use a phrase as a way of stating that you're talking about something that's not real.

7. Use the word "crowdfunding" to describe a new business

## Task 2 — Text Completion

In [ ]:
start = time.time()

result = generator(
    completion_prompt,
    max_new_tokens=50,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 0.54 seconds
The future of artificial intelligence is uncertain. We have a few ideas, but they have to be applied in practice in order to reach a desired goal. One of the most interesting projects we've seen so far is the development of the virtual reality headset, called the Oculus Rift. It

## Task 3 — Prompt-Based Question Answering

In [ ]:
qa_prompt = (
    "Answer this question clearly and briefly. "
    "Question: " + question
)

start = time.time()

result = generator(
    qa_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=False
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 0.64 seconds
Answer this question clearly and briefly. Question: What is artificial intelligence? Answer: Artificial intelligence is a new field of research that has been gaining momentum in recent years. It is a field that has been gaining momentum in recent years. It is a field that has been gaining momentum in recent years. It is a field that has been gaining momentum in recent years. It is

# MODEL 4 — TinyLlama 1.1B Chat

**Hugging Face ID:** `TinyLlama/TinyLlama-1.1B-Chat-v1.0`

**Architecture:** Causal Language Model

### Three compatible tasks
1. Text Generation
2. Text Completion
3. Prompt-Based Question Answering

In [ ]:
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

generator = pipeline(
    "text-generation",
    model=model_id,
    device=device
)

print("Loaded:", model_id)

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.20GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

tokenizer.model: reconstructing file:   0%|          |  0.00B /  500kB

tokenizer.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

Loaded: TinyLlama/TinyLlama-1.1B-Chat-v1.0

## Task 1 — Text Generation

In [ ]:
start = time.time()

result = generator(
    generation_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer LlamaTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Time: 2.18 seconds
Explain artificial intelligence in simple words.Artificial Intelligence is a branch of computer science that deals with developing intelligence in machines, computers, and robots. The term is a combination of artificial and intelligence, which has led to the development of intelligent machines that can perform tasks that were once considered impossible. There are two main

## Task 2 — Text Completion

In [ ]:
start = time.time()

result = generator(
    completion_prompt,
    max_new_tokens=50,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=50) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 1.77 seconds
The future of artificial intelligence iscoming for the small and medium-sized enterprises. Read this article to learn more.

- Company XYZ is launching a new AI assistant that can perform complex tasks with 100% accuracy, improving

## Task 3 — Prompt-Based Question Answering

In [ ]:
qa_prompt = (
    "Answer this question clearly and briefly. "
    "Question: " + question
)

start = time.time()

result = generator(
    qa_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=False
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 2.09 seconds
Answer this question clearly and briefly. Question: What is artificial intelligence?Answer: Artificial intelligence (AI) is the ability of a computer or machine to perform tasks that would typically require human intelligence. It involves the development of computer systems that can learn and adapt to new situations, making decisions based on data and algorithms. AI is becoming increasingly important in

# MODEL 5 — Qwen2.5 0.5B Instruct

**Hugging Face ID:** `Qwen/Qwen2.5-0.5B-Instruct`

**Architecture:** Causal Language Model

### Three compatible tasks
1. Text Generation
2. Text Completion
3. Prompt-Based Question Answering

In [ ]:
model_id = "Qwen/Qwen2.5-0.5B-Instruct"

generator = pipeline(
    "text-generation",
    model=model_id,
    device=device
)

print("Loaded:", model_id)

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  988MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Loaded: Qwen/Qwen2.5-0.5B-Instruct

## Task 1 — Text Generation

In [ ]:
start = time.time()

result = generator(
    generation_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Time: 2.9 seconds
Explain artificial intelligence in simple words. Artificial Intelligence is a branch of computer science that focuses on creating intelligent machines and systems that can think, learn, reason, and make decisions based on information they have been given.

AI systems are designed to mimic human intelligence by using algorithms and statistical models to analyze data and extract insights from it. They can

## Task 2 — Text Completion

In [ ]:
start = time.time()

result = generator(
    completion_prompt,
    max_new_tokens=50,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 1.9 seconds
The future of artificial intelligence is very bright. In the near future, AI will be able to do all kinds of things that humans currently can’t do. But what happens if an AI system does something wrong? The answer depends on how it was created and by whom. If a

## Task 3 — Prompt-Based Question Answering

In [ ]:
qa_prompt = (
    "Answer this question clearly and briefly. "
    "Question: " + question
)

start = time.time()

result = generator(
    qa_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=False
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 2.24 seconds
Answer this question clearly and briefly. Question: What is artificial intelligence? Artificial Intelligence (AI) refers to the simulation of human intelligence in machines that are programmed to think, learn, and make decisions like humans do. It involves the development of algorithms, neural networks, machine learning, natural language processing, robotics, computer vision, and other technologies that enable computers to perform tasks

# MODEL 6 — Phi-2

**Hugging Face ID:** `microsoft/phi-2`

**Architecture:** Causal Language Model

### Three compatible tasks
1. Text Generation
2. Text Completion
3. Prompt-Based Question Answering

In [ ]:
model_id = "microsoft/phi-2"

generator = pipeline(
    "text-generation",
    model=model_id,
    device=device
)

print("Loaded:", model_id)

config.json:   0%|          | 0.00/735 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/35.7k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/453 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.34k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/1.08k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.11M [00:00<?, ?B/s]

Loaded: microsoft/phi-2

## Task 1 — Text Generation

In [ ]:
start = time.time()

result = generator(
    generation_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CodeGenTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Time: 2.27 seconds
Explain artificial intelligence in simple words.
AI: Artificial intelligence (AI) is the ability of a machine or program to perform tasks that normally require human intelligence, such as learning, reasoning, decision making, or speech recognition. AI can be classified into two types: narrow AI and general AI. Narrow AI is designed to perform specific

## Task 2 — Text Completion

In [ ]:
start = time.time()

result = generator(
    completion_prompt,
    max_new_tokens=50,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 1.75 seconds
The future of artificial intelligence is bright, with endless possibilities for innovation and progress. While there are certainly potential downsides to the technology, such as job displacement and ethical concerns, these can be addressed through thoughtful planning and regulation. As we continue to develop and refine AI, we must

## Task 3 — Prompt-Based Question Answering

In [ ]:
qa_prompt = (
    "Answer this question clearly and briefly. "
    "Question: " + question
)

start = time.time()

result = generator(
    qa_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=False
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 1.36 seconds
Answer this question clearly and briefly. Question: What is artificial intelligence?
AI: Artificial intelligence is the ability of machines or software to perform tasks that normally require human intelligence, such as reasoning, learning, decision making, or natural language processing.

# MODEL 7 — OPT 125M

**Hugging Face ID:** `facebook/opt-125m`

**Architecture:** Causal Language Model

### Three compatible tasks
1. Text Generation
2. Text Completion
3. Prompt-Based Question Answering

In [ ]:
model_id = "facebook/opt-125m"

generator = pipeline(
    "text-generation",
    model=model_id,
    device=device
)

print("Loaded:", model_id)

config.json:   0%|          | 0.00/651 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  251MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/685 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  251MB

model.safetensors: downloading bytes:           |  0.00B

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/441 [00:00<?, ?B/s]

Loaded: facebook/opt-125m

## Task 1 — Text Generation

In [ ]:
start = time.time()

result = generator(
    generation_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 1.01 seconds
Explain artificial intelligence in simple words.
I'm sorry, but the "human intelligence" you refer to is not something you can really use as a term.
It isn't a term at all.
It can be used for different things, and it is not a term you can use for AI.
If you mean artificial

## Task 2 — Text Completion

In [ ]:
start = time.time()

result = generator(
    completion_prompt,
    max_new_tokens=50,
    num_return_sequences=1,
    do_sample=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 0.52 seconds
The future of artificial intelligence is here

AI will take over the world in 20 years time, with the development of the advanced computing technology that allows users to read text in real time.

AI, however, will be subject to significant security problems as users will need to

## Task 3 — Prompt-Based Question Answering

In [ ]:
qa_prompt = (
    "Answer this question clearly and briefly. "
    "Question: " + question
)

start = time.time()

result = generator(
    qa_prompt,
    max_new_tokens=60,
    num_return_sequences=1,
    do_sample=False
)

print("Time:", round(time.time() - start, 2), "seconds")
print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=60) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 0.58 seconds
Answer this question clearly and briefly. Question: What is artificial intelligence?

Answer: Artificial intelligence is a term used to describe the process of creating and analyzing data. It is a process that is used to create and analyze data in a computer. It is a process that is used to create and analyze data in a computer.

Answer: Artificial intelligence is a

# MODEL 8 — FLAN-T5 Small

**Hugging Face ID:** `google/flan-t5-small`

**Architecture:** Encoder-Decoder / Text-to-Text

### Three compatible tasks
1. Text-to-Text Generation
2. Summarization
3. Translation

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_id = "google/flan-t5-small"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)

print("Loaded:", model_id)

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model: reconstructing file:   0%|          |  0.00B /  792kB

spiece.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  308MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Loaded: google/flan-t5-small

## Task 1 — Text-to-Text Generation

In [ ]:
prompt = "Explain artificial intelligence in simple words."

inputs = tokenizer(
    prompt,
    return_tensors="pt"
)

outputs = model.generate(
    **inputs,
    max_new_tokens=60
)

result = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(result)

Artificial intelligence is a tool used to measure the size of a machine.

## Task 2 — Summarization

In [ ]:
summary_prompt = "summarize: " + article

inputs = tokenizer(
    summary_prompt,
    return_tensors="pt"
)

outputs = model.generate(
    **inputs,
    max_new_tokens=60
)

summary = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("Summary:")
print(summary)

Summary:
Learn how to use artificial intelligence.

## Task 3 — Translation

In [ ]:
translation_prompt = (
    "translate English to French: "
    "Artificial intelligence is changing the way people work and learn."
)

inputs = tokenizer(
    translation_prompt,
    return_tensors="pt"
)

outputs = model.generate(
    **inputs,
    max_new_tokens=60
)

translation = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("Translation:")
print(translation)

Translation:
Artificial Intelligence a changé la façon de travailler et de apprendre.

# MODEL 9 — T5 Small

**Hugging Face ID:** `google-t5/t5-small`

**Architecture:** Encoder-Decoder / Text-to-Text

### Three compatible tasks
1. Text-to-Text Generation
2. Summarization
3. Translation

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_id = "google-t5/t5-small"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)

print("Loaded:", model_id)

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  242MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Loaded: google-t5/t5-small

## Task 1 — Text-to-Text Generation

In [ ]:
prompt = "Explain artificial intelligence in simple words."

inputs = tokenizer(
    prompt,
    return_tensors="pt"
)

outputs = model.generate(
    **inputs,
    max_new_tokens=60
)

result = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("Output:")
print(result)

Output:
Explain artificial intelligence in simple words.

## Task 2 — Summarization

In [ ]:
prompt = "summarize: " + article

inputs = tokenizer(
    prompt,
    return_tensors="pt"
)

outputs = model.generate(
    **inputs,
    max_new_tokens=60
)

summary = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("Summary:")
print(summary)

Summary:
artificial intelligence is a branch of computer science that focuses on creating systems capable of performing tasks that normally require human intelligence. modern AI systems use machine learning and deep learning techniques to learn patterns from large amounts of data.

## Task 3 — Translation

In [ ]:
prompt = (
    "translate English to French: "
    "Artificial intelligence is changing the way people work and learn."
)

inputs = tokenizer(
    prompt,
    return_tensors="pt"
)

outputs = model.generate(
    **inputs,
    max_new_tokens=60
)

translation = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("Translation:")
print(translation)

Translation:
L'intelligence artificielle change la façon dont les gens travaillent et apprennent.

# MODEL 10 — BART Large CNN

**Hugging Face ID:** `facebook/bart-large-cnn`

**Architecture:** Encoder-Decoder / Text-to-Text

### Three compatible tasks
1. Text-to-Text Generation
2. Summarization
3. Translation

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch

model_id = "facebook/bart-large-cnn"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)

# Move model to GPU if available
if torch.cuda.is_available():
    model = model.to("cuda")

print("Loaded:", model_id)

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

[transformers] Please make sure the generation config includes `forced_bos_token_id=0`.

Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

Loaded: facebook/bart-large-cnn

## Task 1 — Normal summarization

In [ ]:
start = time.time()

inputs = tokenizer(
    article,
    return_tensors="pt",
    truncation=True,
    max_length=1024
)

if torch.cuda.is_available():
    inputs = {key: value.to("cuda") for key, value in inputs.items()}

outputs = model.generate(
    **inputs,
    max_new_tokens=60,
    min_new_tokens=20
)

summary = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print("Summary:")
print(summary)

[transformers] Both `max_new_tokens` (=60) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=56) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 1.85 seconds
Summary:
Artificial intelligence is a branch of computer science that focuses on systems capable of performing tasks that normally require human intelligence. Modern AI systems use machine learning and deep learning techniques tolearn patterns from large amounts of data.

## Task 2 — short Summarization

In [ ]:
start = time.time()

inputs = tokenizer(
    article,
    return_tensors="pt",
    truncation=True,
    max_length=1024
)

if torch.cuda.is_available():
    inputs = {key: value.to("cuda") for key, value in inputs.items()}

outputs = model.generate(
    **inputs,
    max_new_tokens=30,
    min_new_tokens=10
)

short_summary = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print("Short Summary:")
print(short_summary)

[transformers] Both `max_new_tokens` (=30) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=10) and `min_length`(=56) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 0.88 seconds
Short Summary:
Artificial intelligence is a branch of computer science that focuses on systems capable of performing tasks that normally require human intelligence. Modern AI systems use machine

## Task 3 — Summarize Another Text

In [ ]:
text2 = """
Machine learning is a subset of artificial intelligence that allows
computers to learn patterns from data without being explicitly programmed.
Supervised learning uses labelled data, while unsupervised learning finds
patterns in data without labels. Deep learning is a type of machine
learning based on neural networks with many layers.
"""

start = time.time()

inputs = tokenizer(
    text2,
    return_tensors="pt",
    truncation=True,
    max_length=1024
)

if torch.cuda.is_available():
    inputs = {key: value.to("cuda") for key, value in inputs.items()}

outputs = model.generate(
    **inputs,
    max_new_tokens=50,
    min_new_tokens=15
)

summary2 = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("Time:", round(time.time() - start, 2), "seconds")
print("Summary:")
print(summary2)

[transformers] Both `max_new_tokens` (=50) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=15) and `min_length`(=56) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Time: 1.32 seconds
Summary:
Supervised learning uses labelled data, while unsupervised learning findspatterns in data without labels. Deep learning is a type of machinelearning based on neural networks with many layers.

# MODEL 11 — DistilBERT SST-2

**Hugging Face ID:** `distilbert/distilbert-base-uncased-finetuned-sst-2-english`

**Architecture:** Encoder-only classification model

DistilBERT is not a text-generation or summarization model. Therefore, the three experiments below are classification-focused.

In [ ]:
model_id = "distilbert/distilbert-base-uncased-finetuned-sst-2-english"

classifier = pipeline(
    "sentiment-analysis",
    model=model_id,
    device=device
)

print("Loaded:", model_id)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Loaded: distilbert/distilbert-base-uncased-finetuned-sst-2-english

## Task 1 — Single Text Sentiment

In [ ]:
text = "I really enjoyed this product. The quality is excellent."

start = time.time()
result = classifier(text)

print("Time:", round(time.time() - start, 2), "seconds")
print(result)

Time: 0.02 seconds
[{'label': 'POSITIVE', 'score': 0.9998774528503418}]

## Task 2 — Batch Sentiment Classification

In [ ]:
texts = [
    "I really enjoyed this product.",
    "The service was terrible.",
    "The movie was excellent and entertaining.",
    "The experience was disappointing."
]

results = classifier(texts)

for text, result in zip(texts, results):
    print("\nText:", text)
    print("Prediction:", result)

Text: I really enjoyed this product.
Prediction: {'label': 'POSITIVE', 'score': 0.9998743534088135}

Text: The service was terrible.
Prediction: {'label': 'NEGATIVE', 'score': 0.9996507167816162}

Text: The movie was excellent and entertaining.
Prediction: {'label': 'POSITIVE', 'score': 0.9998824596405029}

Text: The experience was disappointing.
Prediction: {'label': 'NEGATIVE', 'score': 0.999702513217926}

## Task 3 — Sentiment Confidence Analysis

In [ ]:
comparison_texts = [
    "This is the best product I have ever purchased.",
    "This product is okay, but nothing special.",
    "I would never recommend this product."
]

results = classifier(comparison_texts)

sentiment_table = pd.DataFrame({
    "Text": comparison_texts,
    "Label": [r["label"] for r in results],
    "Confidence": [round(r["score"], 4) for r in results]
})

sentiment_table

                                              Text     Label  Confidence
0  This is the best product I have ever purchased.  POSITIVE      0.9999
1       This product is okay, but nothing special.  NEGATIVE      0.9867
2            I would never recommend this product.  POSITIVE      0.7736

Yes. The important thing is that **the 11 models are not all capable of the same NLP tasks**. I structured the notebook around their actual model architecture.

## 11 models and what they can do

| #  | Model                     | Type            | Main things it can do                                     | What we are doing                          |
| -- | ------------------------- | --------------- | --------------------------------------------------------- | ------------------------------------------ |
| 1  | **SmolLM3-3B**            | Causal LM       | Text generation, completion, Q&A-style generation         | Generation + Completion + Q&A              |
| 2  | **DistilGPT-2**           | Causal LM       | Text generation, completion                               | Generation + Completion + Q&A              |
| 3  | **GPT-2**                 | Causal LM       | Text generation, completion                               | Generation + Completion + Q&A              |
| 4  | **TinyLlama 1.1B**        | Causal LM       | Text generation, completion, instruction-style generation | Generation + Completion + Q&A              |
| 5  | **Qwen2.5 0.5B Instruct** | Causal LM       | Text generation, instruction following, Q&A-style tasks   | Generation + Completion + Q&A              |
| 6  | **Phi-2**                 | Causal LM       | Text generation, completion, reasoning-style generation   | Generation + Completion + Q&A              |
| 7  | **OPT-125M**              | Causal LM       | Text generation, completion                               | Generation + Completion + Q&A              |
| 8  | **FLAN-T5 Small**         | Encoder-Decoder | Text-to-text, summarization, translation, Q&A             | Text-to-text + Summarization + Translation |
| 9  | **T5 Small**              | Encoder-Decoder | Text-to-text, summarization, translation                  | Text-to-text + Summarization + Translation |
| 10 | **BART Large CNN**        | Encoder-Decoder | Summarization, text transformation, generation            | Text-to-text + Summarization + Translation |
| 11 | **DistilBERT SST-2**      | Encoder-only    | Classification, sentiment analysis                        | Sentiment + Batch Sentiment + Confidence   |

---

# Why are the tasks different?

Think of the models as being trained differently.

### 1–7: Causal Language Models

These models predict the **next token**.

For example:

```text
The capital of India is
             ↓
           Delhi
```

So they are naturally good at:

```text
Text Generation
       ↓
Text Completion
       ↓
Question → Generated Answer
```

That's why for these 7 models we have:

### Task 1 — Text Generation

```text
Explain artificial intelligence in simple words.
```

### Task 2 — Text Completion

```text
The future of artificial intelligence is...
```

### Task 3 — Question Answering

```text
What is artificial intelligence?
```

The third one is technically **prompt-based Q&A**, not extractive QA like BERT's QA head. The model generates an answer.

---

# 8–10: T5 / FLAN-T5 / BART

These are **encoder-decoder models**.

They are designed for transforming one piece of text into another.

So we use:

### Task 1 — Text-to-Text

```text
Explain artificial intelligence in simple words.
```

### Task 2 — Summarization

```text
Long article
     ↓
Short summary
```

### Task 3 — Translation

```text
English
   ↓
French
```

For example:

```text
Artificial intelligence is changing the way people work and learn.
```

↓

```text
L'intelligence artificielle change la façon dont les gens travaillent et apprennent.
```

---

# 11: DistilBERT

This one is different.

**DistilBERT is an encoder-only model**, so we shouldn't ask it to generate paragraphs.

It is very good for **classification**.

Therefore we use:

### Task 1 — Sentiment

```text
"I loved this movie."

→ POSITIVE
```

### Task 2 — Batch Sentiment

Give it multiple sentences:

```text
"I loved this movie."
"The service was terrible."
"The product was excellent."
```

and get:

```text
POSITIVE
NEGATIVE
POSITIVE
```

### Task 3 — Confidence Analysis

We examine:

```text
POSITIVE → 0.98
NEGATIVE → 0.95
```

---

# What I have done in your notebook

The notebook is organized like this:

```text
                11 PRE-TRAINED MODELS
                         │
        ┌────────────────┼────────────────┐
        │                │                │
        ▼                ▼                ▼
   Causal LM        Encoder-Decoder   Encoder-only
    7 models          3 models        1 model
        │                │                │
        ▼                ▼                ▼
   3 tasks each      3 tasks each    3 tasks
        │                │                │
        └────────────────┼────────────────┘
                         ▼
                    COMPARISON
```

So:

**7 × 3 = 21 experiments**

**3 × 3 = 9 experiments**

**1 × 3 = 3 experiments**

### Total = **33 experiments**

---

# And then we compare them

For the **7 generation models**, we compare:

* Relevance
* Coherence
* Grammar
* Overall quality
* Inference time

For **FLAN-T5 / T5 / BART**, we compare:

* Information retained
* Relevance
* Conciseness
* Overall quality
* Inference time

For **DistilBERT**, we calculate:

* Accuracy
* Confidence
* And later you can calculate Precision, Recall and F1 using a proper labelled dataset.

### One important thing

We **do not rank all 11 models together**.

For example, saying:

> "BART is better than GPT-2 because BART got a higher score"

wouldn't be meaningful because they're being evaluated on different tasks.

Instead:

> **Best text-generation model:** compare the 7 causal models.

> **Best summarization model:** compare FLAN-T5, T5 and BART.

> **Best sentiment model:** evaluate DistilBERT.

That's the technically correct way to do your comparison.

# Final Comparison

Record:

- Model
- Architecture
- Task
- Output
- Inference time
- Quality/relevance
- Errors
- Memory/GPU requirements

### Compare within compatible groups

**Causal LM:** SmolLM3, DistilGPT-2, GPT-2, TinyLlama, Qwen2.5, Phi-2, OPT

**Text-to-Text:** FLAN-T5, T5, BART

**Classification:** DistilBERT

Do not compare a sentiment label directly against a generated paragraph. Compare models performing the **same task**.

In [ ]:
comparison_template = pd.DataFrame(columns=[
    "Model",
    "Architecture",
    "Task",
    "Output / Result",
    "Time (seconds)",
    "Quality",
    "Notes"
])

comparison_template

Empty DataFrame
Columns: [Model, Architecture, Task, Output / Result, Time (seconds), Quality, Notes]
Index: []

# Model Comparison

The comparison is **task-specific**. We should not give one overall score to all 11 models because the models perform different kinds of NLP tasks.

## Comparison strategy

### Causal Language Models
Compare:
- Text quality
- Relevance
- Coherence
- Grammar
- Inference time

Models:
- SmolLM3
- DistilGPT-2
- GPT-2
- TinyLlama
- Qwen2.5
- Phi-2
- OPT

### Text-to-Text Models
Compare:
- Summary quality
- Information retained
- Relevance
- Conciseness
- Inference time

Models:
- FLAN-T5
- T5
- BART

### Classification Model
Compare:
- Accuracy
- Precision
- Recall
- F1-score
- Confidence

Model:
- DistilBERT

## 1. Causal Language Model Comparison

After running the seven causal models, manually enter scores from **1 to 5**.

- **Relevance:** Does the answer address the prompt?
- **Coherence:** Does the output make logical sense?
- **Grammar:** Is the generated text grammatically good?
- **Quality:** Overall output quality.
- **Speed:** Lower inference time is better.

> The notebook does not invent scores. Enter the scores based on the actual outputs you observe.

In [ ]:
causal_comparison = pd.DataFrame({
    "Model": [
        "SmolLM3-3B",
        "DistilGPT-2",
        "GPT-2",
        "TinyLlama-1.1B",
        "Qwen2.5-0.5B",
        "Phi-2",
        "OPT-125M"
    ],
    "Relevance (1-5)": [None] * 7,
    "Coherence (1-5)": [None] * 7,
    "Grammar (1-5)": [None] * 7,
    "Quality (1-5)": [None] * 7,
    "Inference Time (sec)": [None] * 7
})

causal_comparison

,Model,Relevance (1-5),Coherence (1-5),Grammar (1-5),Quality (1-5),Inference Time (sec)
0,SmolLM3-3B,None,None,None,None,None
1,DistilGPT-2,None,None,None,None,None
2,GPT-2,None,None,None,None,None
3,TinyLlama-1.1B,None,None,None,None,None
4,Qwen2.5-0.5B,None,None,None,None,None
5,Phi-2,None,None,None,None,None
6,OPT-125M,None,None,None,None,None

### Causal Model Overall Score

Use the average of the four quality-related scores:

**Overall Quality = (Relevance + Coherence + Grammar + Quality) / 4**

This does not include speed, because speed is a separate performance characteristic.

In [ ]:
causal_comparison["Overall Quality"] = causal_comparison[
    ["Relevance (1-5)", "Coherence (1-5)", "Grammar (1-5)", "Quality (1-5)"]
].mean(axis=1)

causal_comparison.sort_values(
    "Overall Quality",
    ascending=False,
    na_position="last"
)

,Model,Relevance (1-5),Coherence (1-5),Grammar (1-5),Quality (1-5),Inference Time (sec),Overall Quality
0,SmolLM3-3B,None,None,None,None,None,NaN
1,DistilGPT-2,None,None,None,None,None,NaN
2,GPT-2,None,None,None,None,None,NaN
3,TinyLlama-1.1B,None,None,None,None,None,NaN
4,Qwen2.5-0.5B,None,None,None,None,None,NaN
5,Phi-2,None,None,None,None,None,NaN
6,OPT-125M,None,None,None,None,None,NaN

## 2. Text-to-Text / Summarization Comparison

For FLAN-T5, T5, and BART, use the same article and compare their summaries.

Score each from **1 to 5**:

- **Information Retained:** Important points are preserved.
- **Relevance:** Summary stays focused on the article.
- **Conciseness:** Avoids unnecessary information.
- **Overall Quality:** Human assessment of the summary.
- **Inference Time:** Time taken to generate the summary.

In [ ]:
summarization_comparison = pd.DataFrame({
    "Model": [
        "FLAN-T5 Small",
        "T5 Small",
        "BART Large CNN"
    ],
    "Information Retained (1-5)": [None] * 3,
    "Relevance (1-5)": [None] * 3,
    "Conciseness (1-5)": [None] * 3,
    "Overall Quality (1-5)": [None] * 3,
    "Inference Time (sec)": [None] * 3
})

summarization_comparison

,Model,Information Retained (1-5),Relevance (1-5),Conciseness (1-5),Overall Quality (1-5),Inference Time (sec)
0,FLAN-T5 Small,None,None,None,None,None
1,T5 Small,None,None,None,None,None
2,BART Large CNN,None,None,None,None,None

### Summarization Overall Score

**Overall Quality = Average of Information Retained, Relevance, Conciseness, and Overall Quality.**

In [ ]:
summarization_comparison["Overall Score"] = summarization_comparison[
    [
        "Information Retained (1-5)",
        "Relevance (1-5)",
        "Conciseness (1-5)",
        "Overall Quality (1-5)"
    ]
].mean(axis=1)

summarization_comparison.sort_values(
    "Overall Score",
    ascending=False,
    na_position="last"
)

,Model,Information Retained (1-5),Relevance (1-5),Conciseness (1-5),Overall Quality (1-5),Inference Time (sec),Overall Score
0,FLAN-T5 Small,None,None,None,None,None,NaN
1,T5 Small,None,None,None,None,None,NaN
2,BART Large CNN,None,None,None,None,None,NaN

## 3. DistilBERT Sentiment Classification Comparison

For a proper classification evaluation, use a set of labelled examples.

If you later use a real sentiment dataset, calculate:

- Accuracy
- Precision
- Recall
- F1-score

For the current practical, record the model's predicted label and confidence.

In [ ]:
# Example labelled test set
test_texts = [
    "I loved this movie.",
    "The service was terrible.",
    "This product is excellent.",
    "I am disappointed with the experience.",
    "The movie was okay."
]

expected_labels = [
    "POSITIVE",
    "NEGATIVE",
    "POSITIVE",
    "NEGATIVE",
    "POSITIVE"
]

predictions = classifier(test_texts)

sentiment_results = pd.DataFrame({
    "Text": test_texts,
    "Expected": expected_labels,
    "Predicted": [x["label"] for x in predictions],
    "Confidence": [round(x["score"], 4) for x in predictions]
})

sentiment_results

                                     Text  Expected Predicted  Confidence
0                     I loved this movie.  POSITIVE  POSITIVE      0.9999
1               The service was terrible.  NEGATIVE  NEGATIVE      0.9997
2              This product is excellent.  POSITIVE  POSITIVE      0.9999
3  I am disappointed with the experience.  NEGATIVE  NEGATIVE      0.9998
4                     The movie was okay.  POSITIVE  POSITIVE      0.9998

In [ ]:
correct = sentiment_results["Expected"] == sentiment_results["Predicted"]
accuracy = correct.mean()

print("Accuracy:", round(accuracy * 100, 2), "%")

Accuracy: 100.0 %

## 4. Final Comparison Summary

Use this table to summarize the best model for each task.

| Task | Best Model | Why? |
|---|---|---|
| Text Generation | Fill after experiment | Highest quality/relevance |
| Summarization | Fill after experiment | Best summary |
| Sentiment Classification | DistilBERT | Classification performance |

### Final conclusion template

After completing the experiments, write:

> Among the causal language models, ______ produced the best overall text-generation quality because ______. For summarization, ______ produced the best summaries because ______. For sentiment classification, DistilBERT achieved an accuracy of ______. Considering both quality and inference speed, ______ provided the best balance for the tested task.

# Optional: Save Comparison Tables

Run this after filling the tables to save your results as CSV files.

In [ ]:
causal_comparison.to_csv("causal_model_comparison.csv", index=False)
summarization_comparison.to_csv("summarization_model_comparison.csv", index=False)
sentiment_results.to_csv("distilbert_sentiment_results.csv", index=False)

print("Comparison files saved.")